### ISSUE TITLE
no refreshing on data changes

### ISSUE THREAD

**Issue by nferruzzi** [sbertix/CollectionUI#2]
Hi!
thank you for wrapping the collection view, I was just going to try it myself :) 
I've just started testing the component and so far looks promising but it doesn't refresh the collection when the data model changes. The view is properly bound to the model changes and from debugging the Collection I can see that is recreated every time the data changes but the coordinator is called just once and therefore it doesn't reflect the new data.
Can you help?

**Comment by sbertix** [comment]
I'll try to investigate it and and push a new commit with a solution 💪 
@nferruzzi
