### ISSUE TITLE
Changing a SwiftUI attribute does not immediately refresh cell

### ISSUE THREAD

**Issue by avi-screenovate** [sbertix/CollectionUI#5]
I am using the following code:
```
                CollectionView(pendingQueue.items, id: \.self) { item in
                    image(for: item)
                        .conditionallyFill(item.image != nil)
                        .frame(width: 75, height: 75, alignment: .center)
                        .clipped()
                        .border(selectedItem == item ? Color(Asset.Colors.selectedBorder.name) : Color.clear, width: 4)
                        .onTapGesture {
                            selectedItem = item
                        }
                }
                .axis(.horizontal)
                .indicators(false)
                .itemSpace(.fixed(8))
                .bounce(false)
                .itemSize(.init(widthDimension: .absolute(75), heightDimension: .absolute(75)))
                .groupSize(.init(widthDimension: .absolute(75), heightDimension: .absolute(75)))
                .clipped()
```

I have verified that the border color is chosen correctly when I tap on an image.  However, the cell does not change appearance unless I scroll far enough away to cause the cell to be reused, and then back.

How can I force the cell to redraw immediately?

**Comment by sbertix** [comment]
Hey @avi-screenovate, 

I haven't really been maintaining this repo… this was written in really early stages of **SwiftUI**, and it hasn't been updated since, so outcomes might differ a lot from expectations, when relying on this.  
I might update this, but for now maybe try adding a different `.id` to your cell for the different stages, something along the lines of…

```swift
image(for: item)
    .conditionallyFill(item.image != nil)
    .frame(width: 75, height: 75, alignment: .center)
    .clipped()
    .border(selectedItem == item ? Color(Asset.Colors.selectedBorder.name) : Color.clear, width: 4)
    .id("\(item).\(selectedItem == item)")
    .onTapGesture {
        selectedItem = item
    }
```

This might as well not work though.

**Comment by avi-screenovate** [comment]
I ended up "forking" your code and pulling it into my project.  I then made some tweaks to handle some layout requirements.  On this issue specifically, I ended up going that route, by generating a new id whenever the state of the model changes.  Unfortunately, this introduces a flicker as the change is animated.

**Comment by sbertix** [comment]
I mean, if you have any suggestions or PR, feel free to submit them 😊 
Again, I might be working on this again in the near future but no promises.
